### ISSUE TITLE
no URL specified

### ISSUE THREAD

**Issue by johnjelinek** [halcyon/asdf-java#20]
```
$ asdf install java adopt-openjdk-8u222-b10
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

I'm running this on a Raspberry Pi 4B+.

**Comment by halcyon** [comment]
Please post the results of `uname -m` and I will attempt to rectify.

**Comment by jknichel** [comment]
I'm getting the same issue:
```
$ asdf install java adopt-openjdk-12.0.2+10.2
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```
And since you asked the person above:
```
$ uname -m
x86_64
```

**Comment by halcyon** [comment]
@jknichel That's because AdoptOpenJDK only has a build of this for mac. I presume you are not running on a mac.

If you look here, you'll see the latest version they have for linux is `12.0.2+10` https://adoptopenjdk.net/releases.html?variant=openjdk12&jvmVariant=hotspot

Apologize for the inconvenience, and for the fact that asdf-java doesn't (yet) filter out builds on platforms that don't exist.

**Comment by Hacklor** [comment]
I came across the same issue on Ubuntu. Developed on Mac initially, but want to run it on Ubuntu instead. Unfortunately the non-adopt options are limited. Any change this can be approved?
Are there providers that have versions for Mac and Ubuntu, so that I can install on both using the `.tool-versions` file? That would be great!

**Comment by halcyon** [comment]
@Hacklor Which version of AdoptOpenJDK are you attempting to install on Ubuntu?

**Comment by halcyon** [comment]
Paging @johnjelinek, I'll be closing this issue if I don't hear back from you in 7 days.  You can of course re-open it, or open a new one upon your return.
