### ISSUE TITLE
Update Oracle JDK to latest versions

### ISSUE THREAD

**Issue by x80486** [halcyon/asdf-java#7]
It would be great to have these in sync:

- Java SE `8u211` / Java SE `8u212`
- Java SE `11.0.3` (LTS)
- Java SE `12.0.1`

Reference: https://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by halcyon** [comment]
If I recall correctly, the reason these were removed & not included is because they require authentication to download. The older versions currently in asdf-java do not require authentication. If you can provide links to the latest versions that don't require one to be logged in with an Oracle user, I'll add them.

**Comment by x80486** [comment]
Until now, I always download those directly. You would only need to accept some license:

```shell
[x80486@uplink no_backup]$ curl -fLC - --progress-bar --retry 3 --retry-delay 3 -b oraclelicense=accept-securebackup-cookie https://download.oracle.com/otn-pub/java/jdk/12.0.1+12/69cfe15208a647278a19ef0990eea691/jdk-12.0.1_linux-x64_bin.tar.gz --output jdk-12.0.1_linux-x64_bin.tar.gz
################################################################################################################################################################### 100.0%
[x80486@uplink no_backup]$ tar -zxf jdk-12.0.1_linux-x64_bin.tar.gz 
[x80486@uplink no_backup]$ ll jdk-12.0.1
jdk-12.0.1/                      jdk-12.0.1_linux-x64_bin.tar.gz  
[x80486@uplink no_backup]$ ll jdk-12.0.1/
total 32K
drwxr-xr-x  2 x80486 4.0K Jun 29 10:14 bin/
drwxr-xr-x  5 x80486 4.0K Jun 29 10:14 conf/
drwxr-xr-x  3 x80486 4.0K Jun 29 10:14 include/
drwxr-xr-x  2 x80486 4.0K Jun 29 10:14 jmods/
drwxr-xr-x 72 x80486 4.0K Jun 29 10:14 legal/
drwxr-xr-x  5 x80486 4.0K Jun 29 10:14 lib/
drwxr-xr-x  3 x80486 4.0K Jun 29 10:14 man/
-rw-r--r--  1 x80486 1.3K Apr  2 02:49 release
```

**Comment by halcyon** [comment]
Perfect, thank you! I'll add them in shortly.

**Comment by x80486** [comment]
Shortcut...these are the URLs:

- Java SE Development Kit `12.0.1` – https://download.oracle.com/otn-pub/java/jdk/12.0.1+12/69cfe15208a647278a19ef0990eea691/jdk-12.0.1_linux-x64_bin.tar.gz
- Java SE Development Kit `11.0.3` – https://download.oracle.com/otn/java/jdk/11.0.3+12/37f5e150db5247ab9333b11c1dddcd30/jdk-11.0.3_linux-x64_bin.tar.gz
- Java SE Development Kit `8u211` – https://download.oracle.com/otn/java/jdk/8u211-b12/478a62b7d4e34b78b671c754eaaf38ab/jdk-8u211-linux-x64.tar.gz
- Java SE Development Kit `8u212` – https://download.oracle.com/otn/java/jdk/8u212-b10/59066701cf1a433da9770636fbc4c9aa/jdk-8u212-linux-x64.tar.gz

**Comment by halcyon** [comment]
@x80486 It works for `jdk 12.0.1`, which I will add - but I believe it's likely that's because it's in `otn-pub`. If you look closely at the other URLs, you'll find that they are `otn` and that they are protected by Oracle's SSO. If you use the curl command you provided me earlier, you'll find the `otn` URLs actually redirect to oracle's SSO.

**Comment by x80486** [comment]
All right! No problem. I usually use the OpenJDK and Zulu builds :sweat_smile:, so if Oracle is _getting funny_ about theirs, then there is nothing we can do :sunglasses:
