### ISSUE TITLE
Amazon Corretto JDK is not available in data tsv

### ISSUE THREAD

**Issue by thuandt** [halcyon/asdf-java#98]
Amazon Corretto JDK is available in `https://joschi.github.io/java-metadata/metadata/all.json` and `https://joschi.github.io/java-metadata/metadata/ga.json`, but it's not including in [`ga/${os}/${arch}/jdk.json`](https://github.com/halcyon/asdf-java/blob/master/update_data.bash#L20)

cc @joschi and @halcyon

**Comment by joschi** [comment]
@thuandt Thanks for reporting this!

It was a bug in the upstream project (https://github.com/joschi/java-metadata/) which assigned the wrong image type (JDK or JRE) to the Corretto distributions in some cases. I've fixed that bug and with [the next update of the local metadata files](https://github.com/halcyon/asdf-java/actions?query=workflow%3A%22Update+Java+release+data%22+branch%3Amaster) this will be fixed for `asdf-java`, too.

On a side note, Amazon Corretto is one of the few Java distributions which doesn't offer machine readable data of their releases which can be reasonably parsed.
Feel free to amplify this tweet so that they might change it: https://twitter.com/joschi83/status/1276489559220662272

**Comment by joschi** [comment]
Good timing, here it is: 670cedc82f2bc3e90f389bfba315a0deec416354
